### ISSUE TITLE
Running Blockchain and BlockchainPaymentShop

### ISSUE THREAD

**Issue by ngduytra** [dpedwards/dotnet-core-blockchain-payment-solution#2]
i'm trying to running Blockchain and BlockChainPaymentShop , but they all take out this error. Please support to me , thank you very much!
![image](https://user-images.githubusercontent.com/33368418/71428698-fdca7100-26f4-11ea-9e39-ac3cc48bb256.png)

**Comment by dpedwards** [comment]
Hello please take a look at this: https://stackoverflow.com/questions/57746667/the-project-web-must-provide-a-value-for-configuration-error-after-migrating

**Comment by dpedwards** [comment]
Use .NET Core 2.2 Version to run this project or delete 

> Microsoft.AspNetCore.Razor.Design

 reference which isn't needed at all as _Razor.Design_ for .NET Core 3.0 because it's now part of AspNetCoe library. 
Check this source if you need more information: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio]).
